# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    reviewers:
      - "maintainers"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    reviewers:
      - "maintainers"
